# Generated by Django 2.1.1 on 2018-09-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_auto_20180927_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_who', to='grumblr.Person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_who', to='grumblr.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='age',
            field=models.IntegerField(blank=True, default='99'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='bio',
            field=models.CharField(blank=True, default='the user does not want to say anything', max_length=420),
        ),
        migrations.AddField(
            model_name='person',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='grumblr.Relationship', to='grumblr.Person'),
        ),
    ]
