# Generated by Django 2.1.1 on 2018-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_auto_20181003_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile-photos'),
        ),
    ]
