# Generated by Django 2.1.1 on 2018-10-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_auto_20181003_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lastname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
