# Generated by Django 2.1.1 on 2018-10-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
